- name: One Love project provisioning
  hosts: all
  pre_tasks:
    - include: roles/common/pre_tasks/main.yml
  roles:
    - common

- name: One Love project provisioning
  hosts: vagrant
  roles:
    - vagrant

- name: One Love project provisioning
  hosts: all
  roles:
    - mongodb
    - onelove
    - nginx
