---
- name: add onelove service
  sudo: yes
  template:
    src: onelove.service.j2
    dest: /lib/systemd/system/onelove.service
    owner: root
    group: root
  notify:
    - restart onelove

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start onelove service
  sudo: yes
  service:
    name: onelove
    enabled: "{{ onelove_enabled }}"
    state: "{{ onelove_state }}"
