---
- name: add rabbitmq service
  become: yes
  template:
    src: rabbitmq.service.j2
    dest: /lib/systemd/system/rabbitmq.service
    owner: root
    group: root
  notify:
    - restart rabbitmq

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: start rabbitmq service
  become: yes
  service:
    name: rabbitmq
    enabled: yes
    state: started
