---
version: '2'
services:
  frontend:
    image: onelove/frontend
    volumes:
      - ./projects/frontend:/usr/src/app
    command: ./bin/dev.sh
    ports:
      - "8080:8080"

  backend:
    image: onelove/backend
    volumes:
      - ./projects/backend:/usr/src/app
      - /tmp/.cache:/root/.cache
    command: ./bin/dev.sh
    ports:
      - "5000:5000"
    links:
      - mongodb:mongodb

  worker:
    image: onelove/backend
    volumes:
      - ./projects/backend:/usr/src/app
      - /tmp/.cache:/root/.cache
    command: ./bin/worker_dev.sh
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest

  registrator:
    image: gliderlabs/registrator:latest
    command: consul://consul:8500
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul:consul

  consul:
    image: consul:latest
    command: agent -data-dir=/consul/data -config-dir=/consul/config -dev -client 0.0.0.0
    ports:
      - "8500:8500"
