---
- name: install packages for docker repository
  sudo: yes
  apt:
    pkg: "{{ item.name }}"
    state: latest
  with_items:
    - name: apt-transport-https
    - name: ca-certificates

- name: add docker repository key
  sudo: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    state: present

- name: add docker repository
  sudo: yes
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
    state: present
    update_cache: yes
