- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: install packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
  notify:
    - restart openntpd

- name: link docker.io to docker
  sudo: yes
  file:
    src: /usr/bin/docker
    dest: /usr/bin/docker.io
    owner: root
    group: root
    state: link

- name: install pip packages
  sudo: yes
  with_items: common_pip_packages
  pip:
    name: "{{ item.name }}"
    state: present
