---
- name: update apt
  become: yes
  apt:
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: docker.io
    state: latest

- name: start docker
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: add common services
  become: yes
  with_items: "{{ common_services }}"
  template:
    src: "{{ item.name }}.service.j2"
    dest: "/lib/systemd/system/{{ item.name }}.service"
    owner: root
    group: root
  notify:
    - restart consul
    - restart registrator

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: start common services
  become: yes
  with_items: "{{ common_services }}"
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: started

- name: install common packages
  become: yes
  with_items: "{{ common_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest
