- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: install packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: restart openntpd
  sudo: yes
  service:
    name: openntpd
    enabled: yes
    state: restarted
