- name: restart celery
  sudo: yes
  command: supervisorctl restart celery

- name: load migrations
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  django_manage:
    app_path: /var/www/onelove
    command: migrate
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"

- name: restart uwsgi
  sudo: yes
  service:
    name: uwsgi
    enabled: yes
    state: started
