- name: ensure supervisor group exists
  sudo: yes
  group:
    name: supervisor
    state: present

- name: ensure api_user exists
  sudo: yes
  user:
    name: "{{ api_user }}"
    groups: supervisor,sudo

- name: configure nginx user
  sudo: yes
  user:
    name: nginx
    groups: www-data
    state: present

- name: ensure api_user have bin dir
  sudo: yes
  file:
    path: "~{{ api_user}}/bin"
    owner: "{{ api_user }}"
    group: "{{ api_user }}"
    state: directory

- name: copy runserver script
  sudo: yes
  template:
    src: runserver.sh.j2
    dest: "~{{ api_user }}/bin/runserver.sh"
    owner: "{{ api_user }}"
    group: "{{ api_user }}"
    mode: 0755
