- name: ensure supervisor group exists
  sudo: yes
  group:
    name: supervisor
    state: present

- name: ensure webapp_user exists
  sudo: yes
  user:
    name: "{{ webapp_user }}"
    groups: supervisor,sudo
