---
- name: copy postgres service file
  sudo: yes
  copy:
    src: postgres.service
    dest: /tmp/postgres.service

- name: enable postgres service
  sudo: yes
  command: fleetctl start postgres.service
  args:
    chdir: /tmp
