---
- name: install repo
  sudo: yes
  with_items: vagrant_apt_repos
  template:
    src: "{{ item.name }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item.name }}.list"
    owner: root
    group: root

- name: install repo keys
  sudo: yes
  with_items: vagrant_apt_repos
  apt_key:
    url: "{{ item.key }}"
    state: present

- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: clone one love repos
  with_items: vagrant_repos
  git:
    repo: "{{ item.url }}"
    dest: /vagrant/projects/{{ item.name }}
    accept_hostkey: yes
    update: no

- name: put project in path
  sudo: yes
  copy:
    src: project-path.sh
    dest: /etc/profile.d/project-path.sh
    owner: root
    group: root
    mode: 0644

- name: install packages
  sudo: yes
  with_items: vagrant_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install requirements
  sudo: yes
  pip:
    requirements: /vagrant/projects/backend/requirements_dev.txt

- name: install npm
  sudo: yes
  shell: npm install -g npm

- name: install node modules
  sudo: yes
  shell: npm install
  args:
    chdir: /vagrant/projects/frontend
    creates: /vagrant/projects/frontend/node_modules

- name: configure backend
  sudo: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest consul-template -once -config /usr/src/app/consul/onelove.conf"

- name: create default admin
  sudo: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest /usr/src/app/create_default_admin.py"
