---
- name: install repo
  become: yes
  with_items: "{{ vagrant_apt_repos }}"
  template:
    src: "{{ item.name }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item.name }}.list"
    owner: root
    group: root

- name: install repo keys
  become: yes
  with_items: "{{ vagrant_apt_repos }}"
  apt_key:
    url: "{{ item.key }}"
    state: present
    validate_certs: no

- name: update apt
  become: yes
  apt:
    update_cache: yes

- name: clone one love repos
  with_items: "{{ vagrant_repos }}"
  git:
    repo: "{{ item.url }}"
    dest: /vagrant/projects/{{ item.name }}
    accept_hostkey: yes
    update: no

- name: put project in path
  become: yes
  copy:
    src: project-path.sh
    dest: /etc/profile.d/project-path.sh
    owner: root
    group: root
    mode: 0644

- name: install packages
  become: yes
  with_items: "{{ vagrant_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install requirements
  become: yes
  pip:
    requirements: /vagrant/projects/backend/requirements_dev.txt

- name: install node modules
  npm:
    path: /vagrant/projects/frontend

- name: configure backend
  become: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest consul-template -once -config /usr/src/app/consul/onelove_dev.conf"

- name: create default admin
  become: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest /usr/src/app/create_default_admin.py"
