---
- name: clone one love repos
  with_items: vagrant_repos
  git:
    repo: "{{ item.url }}"
    dest: /vagrant/projects/{{ item.name }}
    accept_hostkey: yes
    update: no

- name: put api project in path
  sudo: yes
  copy:
    src: api-path.sh
    dest: /etc/profile.d/api-path.sh
    owner: root
    group: root
    mode: 0644

- name: configure backend from consul
  sudo: yes
  command: "docker run -it --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest consul-template -once -config /usr/src/app/consul/onelove.conf"

- name: create default admin
  sudo: yes
  command: "docker run -it --rm -v /vagrant/projects/backend:/usr/src/app --link mongodb:mongodb onelove/backend:latest ./create_default_admin.py"
