- name: deploy workers if inside vagrant
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vm" in group_names'
  file:
    src: /vagrant/workers
    dest: "~{{ webapp_user }}/workers"
    state: link
  tags:
    - deploy

- name: deploy workers if outside vagrant
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vm" not in group_names'
  git:
    repo: https://github.com/mekanix/one-love-workers
    dest: "~{{ webapp_user }}/workers"
    accept_hostkey: yes
    depth: 1
  tags:
    - deploy

