- name: install packages
  sudo: yes
  with_items: worker_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  pip:
    requirements: /vagrant/workers/requirements.txt
    virtualenv: ~/.virtualenvs/workers
    state: latest
