- name: install packages
  sudo: yes
  with_items: worker_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: ensure /var/repos is directory
  sudo: yes
  file:
    path: /var/repos
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
    state: directory

- name: install pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  pip:
    requirements: /vagrant/workers/requirements.txt
    virtualenv: ~/.virtualenvs/workers
    state: latest

- name: ensure /var/log/one-love exists
  sudo: yes
  file:
    path: /var/log/one-love
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
    state: directory

- name: configure supervisor
  sudo: yes
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    owner: root
    group: root
  notify:
    - stop supervisor
    - start supervisor

- name: configure supervisor for workers
  sudo: yes
  template:
    src: supervisor.j2
    dest: /etc/supervisor/conf.d/workers.conf
    owner: root
    group: root
  notify:
    - reload supervisor config
    - update supervisor process
