---
vagrant_packages:
  - name: nodejs-legacy
  - name: npm
  - name: python-pip
  - name: python-dev
  - name: tmux

vagrant_repos:
  - name: backend
    url: https://github.com/one-love/backend
  - name: frontend
    url: https://github.com/one-love/web-client
  - name: nginx
    url: https://github.com/one-love/docker-nginx
