---
- name: start consul
  become: yes
  service:
    name: consul
    state: started

- name: start mongodb
  become: yes
  service:
    name: mongodb
    state: started

- name: start rabbitmq
  become: yes
  service:
    name: rabbitmq
    state: started

- name: update docker images
  become: yes
  with_items: "{{ vagrant_always_images }}"
  shell: docker pull {{ item.image }}


- name: set password
  command: "curl -X PUT http://172.17.42.1:8500/v1/kv/password -d {{ db_password }}"

- name: copy cert
  copy:
    src: roles/vagrant/files/onelove.crt
    dest: /tmp/cert
    mode: 0644

- name: set cert
  command: curl -X PUT http://172.17.42.1:8500/v1/kv/loadbalancer/crt --data-binary @/tmp/cert

- name: remove cert from file system
  file:
    path: /tmp/cert
    state: absent

- name: copy key
  copy:
    src: roles/vagrant/files/onelove.key
    dest: /tmp/key
    mode: 0644

- name: set key
  command: curl -X PUT http://172.17.42.1:8500/v1/kv/loadbalancer/key --data-binary @/tmp/key

- name: remove key from file system
  file:
    path: /tmp/key
    state: absent

- name: set secret key
  become: yes
  command: "curl -X PUT http://172.17.42.1:8500/v1/kv/onelove/secret_key -d {{ onelove_secret_key }}"

- name: configure backend
  become: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest consul-template -once -config /usr/src/app/consul/onelove_dev.conf"
