- name: install postgresql
  sudo: yes
  apt:
    pkg: postgresql-9.3
    state: latest

- name: install python-psycopg2
  sudo: yes
  apt:
    pkg: python-psycopg2
    state: latest

- name: install libpq-dev
  sudo: yes
  apt:
    pkg: libpq-dev
    state: latest
