- name: deploy onelove
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  git:
    repo: https://github.com/one-love/web
    dest: /var/www/onelove
    accept_hostkey: yes
    depth: 1
  notify:
    - restart uwsgi
  tags:
    - deploy

- name: configure web app
  sudo: yes
  template:
    src: __init__.py.j2
    dest: /var/www/onelove/project/settings/__init__.py
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
  notify:
    - restart uwsgi

- name: configure web app for development
  sudo: yes
  template:
    src: __init__.py.j2
    dest: /vagrant/web/project/settings/__init__.py
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"

- name: install common pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  pip:
    requirements: /var/www/onelove/requirements_common.txt
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
    state: present

- name: install production pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  pip:
    requirements: /var/www/onelove/requirements_prod.txt
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
    state: present

- name: install development pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vagrant" in group_names'
  pip:
    requirements: /vagrant/web/requirements_dev.txt
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
    state: present

- name: collect static files
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  django_manage:
    command: collectstatic
    app_path: /var/www/onelove
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
  tags:
    - deploy

- name: remove .pyc files
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  command: find . -name '*.pyc' -delete chdir=/var/www/onelove
  notify:
    - restart uwsgi
  tags:
    - deploy

- name: migrate DB
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  django_manage:
    app_path: /var/www/onelove
    command: migrate
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
