- name: deploy onelove if inside vagrant
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vagrant" in group_names'
  file:
    src: /vagrant/web
    dest: /var/www/onelove
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
    state: link
  notify:
    - load migrations
    - restart uwsgi
  tags:
    - deploy

- name: deploy onelove if outside vagrant
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vagrant" not in group_names'
  git:
    repo: https://github.com/mekanix/one-love-web
    dest: /var/www/onelove
    accept_hostkey: yes
    depth: 1
  notify:
    - load migrations
    - restart uwsgi
  tags:
    - deploy

- name: configure web app
  sudo: yes
  template:
    src: __init__.py.j2
    dest: /var/www/onelove/onelove/settings/__init__.py
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
  notify:
    - restart uwsgi

- name: install pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  pip:
    requirements: /var/www/onelove/requirements.txt
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
    state: present

- name: collect static files
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  django_manage:
    command: collectstatic
    app_path: /var/www/onelove
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
  tags:
    - deploy

- name: remove .pyc files
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  command: find . -name '*.pyc' -delete chdir=/var/www/onelove
  notify:
    - restart uwsgi
  tags:
    - deploy
