- name: deploy onelove if inside vagrant
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vm" in group_names'
  file:
    src: /vagrant/web
    dest: /var/www/onelove
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
    state: link
  notify:
    - reload uwsgi
  tags:
    - deploy

- name: deploy onelove if outside vagrant
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  when: '"vm" not in group_names'
  git:
    repo: https://github.com/mekanix/one-love-web
    dest: /var/www/onelove
    accept_hostkey: yes
    depth: 1
  notify:
    - reload uwsgi
  tags:
    - deploy

- name: install pip packages
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  pip:
    requirements: /var/www/onelove/requirements.txt
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
    state: present

- name: collect static files
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  django_manage:
    command: collectstatic
    app_path: /var/www/onelove
    virtualenv: "~{{ webapp_user }}/.virtualenvs/web"
  tags:
    - deploy
